embedding_size: 64
cf_model: lightgcn

tau: 0.2
n_ui_layers: 4
n_mm_layers: 2

# mm_fuse_type: [sum, att, max]
mm_fuse_type: [att]

# knn_k: [2, 4, 6, 8, 10, 20, 40, 60]
# n_aspects: [1, 2, 4, 8, 16, 32, 64]
# c_weight : [1e-03, 1e-02, 0.1, 1.0, 2.0]
# reg_weight : [1e-03, 1e-02, 0.1, 1.0, 2.0]
# uia_weight: [1e-03, 1e-02, 0.1, 1.0, 2.0]

hyper_parameters: ["mm_fuse_type", "knn_k", "n_aspects"]
