# Common Features
USER_ID_FIELD: userID
ITEM_ID_FIELD: itemID

filter_out_cod_start_users: True

inter_file_name: 'baby.inter'

# name of features
vision_feature_file: 'image_feat.npy'
text_feature_file: 'text_feat.npy'

field_separator: "\t"

knn_k: [20] # baby
n_aspects: [64] # baby
c_weight : [0.01] # baby
reg_weight: [0.01] # baby