# Common Features
USER_ID_FIELD: userID
ITEM_ID_FIELD: itemID

filter_out_cod_start_users: True

inter_file_name: 'baby.inter'

# name of features
vision_feature_file: 'image_feat.npy'
text_feature_file: 'text_feat.npy'

field_separator: "\t"

knn_k: [8] # baby
n_aspects: [8] # baby
c_weight : [0.01] # baby
reg_weight: [0.01] # baby
uia_weight: [0.1]
t_interval: [6] #baby
