# Common Features
USER_ID_FIELD: userID
ITEM_ID_FIELD: itemID

filter_out_cod_start_users: True

inter_file_name: 'clothing.inter'

# name of features
vision_feature_file: 'image_feat.npy'
text_feature_file: 'text_feat.npy'


field_separator: "\t"

knn_k: [8] # clothing
n_aspects: [8] # clothing
c_weight : [0.01] # clothings
reg_weight: [2.0] # clothing