# Common Features
USER_ID_FIELD: userID
ITEM_ID_FIELD: itemID

filter_out_cod_start_users: True

inter_file_name: 'clothing.inter'

# name of features
vision_feature_file: 'image_feat.npy'
text_feature_file: 'text_feat.npy'


field_separator: "\t"

knn_k: [4] # microlens
n_aspects: [32] # microlens
c_weight : [0.01] # microlens
reg_weight: [0.01] # microlens
uia_weight: [0.1] # microlens
t_interval: [7] # microlens
